---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_home: "~"
dotfiles_repo: git@github.com:jgeraerts/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .tmux.conf
#  - .gitignore
#  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ag
  - azure-cli
  - bear
  - borkdude/brew/clj-kondo
  - ccls
  - cmake
  - docker-compose
  - ditaa
  - ffmpeg
  - arm-gcc-bin
  - git
  - go
  - gpg
  - haproxy
  - ispell
  - jenv
  - jq
  - leiningen
  - mariadb
  - maven
  - nvm
  - open-ocd
  - postgresql
  - plantuml
  - platformio
  - protobuf
  - python3
  - rclone
  - ripgrep
  - tmux
  - unrar
  - yarn
  - youtube-dl

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/services
  - homebrew/cask-drivers
  - osx-cross/avr
  - osx-cross/arm
  - AdoptOpenJDK/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - amethyst
  - bitwarden
  - firefox
  - slack
  - iterm2
  - intellij-idea
  - spotify
  - keepassxc
  - adoptopenjdk8
  - adoptopenjdk11
  - emacs
  - emacsclient
  - docker
  - wireshark
  - vlc
  - google-chrome
  - syncthing
  - jprofiler

osx_script: "~/.osx --no-restart"

post_provision_tasks: []

projects: "~/projects"
