---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_home: "~"
dotfiles_repo: git@github.com:jgeraerts/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .tmux.conf
#  - .gitignore
#  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages:
  - ag
  - azure-cli
  - awscli
  - bear
  - borkdude/brew/babashka 
  - borkdude/brew/clj-kondo
  - cairo
  - ccls
  - clojure
  - cloudentity/tap/oauth2c
  - cmake
  - colima
  - d2
  - docker
  - docker-credential-helper
  - ditaa
  - eksctl
  - ffmpeg
  - fx
  - arm-gcc-bin
  - giflib
  - git
  - go
  - gpg
  - haproxy
  - htop
  - ispell
  - jenv
  - jpeg
  - jq
  - k9s
  - kubectl
  - leiningen
  - libffi
  - libpng
  - librsvg
  - maven
  - nvm
  - open-ocd
  - oauth2c
  - pam-reattach
  - pango
  - pipx
  - poetry
  - postgresql
  - pkg-config
  - plantuml
  - platformio
  - protobuf
  - pspg
  - python3
  - rclone
  - ripgrep
  - rustup-init
  - stunnel
  - tmux
  - zlib

homebrew_taps:
  - osx-cross/avr
  - osx-cross/arm

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - bitwarden
  - emacs
  - firefox
  - google-chrome
  - intellij-idea
  - iterm2
  - jprofiler
  - microsoft-remote-desktop
  - secretive
  - session-manager-plugin
  - signal
  - slack
  - spotify
  - syncthing
  - temurin@11
  - temurin@17
  - temurin@21
  - tigervnc-viewer
  - vlc
  - wireshark


osx_script: "~/.osx --no-restart"

post_provision_tasks: []

projects: "~/projects"
