---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_home: "~"
dotfiles_repo: git@github.com:jgeraerts/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .tmux.conf
#  - .gitignore
#  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - go
  - gpg
  - jq
  - git
  - python3
  - tmux
  - mariadb
  - postgresql
  - yarn
  - leiningen
  - maven
  - docker-compose
  - haproxy
  - jenv
  - nvm

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/services
  - AdoptOpenJDK/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - slack
  - iterm2
  - intellij-idea
  - spotify
  - keepassxc
  - google-drive-file-stream
  - adoptopenjdk8
  - adoptopenjdk11
  - emacs
  - docker
  
osx_script: "~/.osx --no-restart"

post_provision_tasks: []

projects: "~/projects"
