---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

  tasks:
    - name: emacs config
      git:
        repo: git@github.com:jgeraerts/dot-emacs.d.git
        dest: "~/.emacs.d"
        accept_hostkey: yes
      become: false
      tags:
        - dotfiles

    - name: "ensure project directory"
      file:
        path: "{{ projects }}"
        state: directory
      tags:
        - projects

    - name: "clone oh my zsh"
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "~/.oh-my-zsh"
      become: false
      tags:
        - dotfiles

    - name: "create .tmux directory"
      file:
        path: "~/.tmux/plugins"
        state: directory
      become: false
      tags:
        - dotfiles

    - name: "clone tmux plugin manager"
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"
      become: false
      tags:
        - dotfiles

    - name: "clone my dotfiles"
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_repo_local_destination }}"
        accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
        
      become: false
      tags:
        - dotfiles

    - name: Link dotfiles into home folder.
      file:
        src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
        dest: "{{ dotfiles_home }}/{{ item }}"
        state: link
      become: false
      with_items: "{{ dotfiles_files }}"
      tags:
        - dotfiles
    

# todo maven settings.xml, projects checkout, iterm2 setup, haproxy ssh config
